require:
  - rubocop-minitest
  - rubocop-rails

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  Max: 20
  Exclude:
    - 'test/*'

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/*'
    -
Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
