# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rails', '7.0.7.2'

gem 'active_model_serializers'
gem 'activerecord-session_store'
gem 'ahoy_matey'
gem 'auto_strip_attributes'
gem 'bootsnap', require: false
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-sass'
gem 'bootstrap-tab-history-rails'
gem 'country_select'
gem 'devise'
gem 'devise_invitable'
gem 'sitemap_generator'
gem 'eventbrite_sdk'
gem 'font-awesome-sass', '~> 4.7.0' # Prefer V4 icon styles
gem 'friendly_id'
gem 'geocoder'
gem 'gravtastic'
gem 'handlebars_assets'
gem 'httparty'
gem 'i18n_data'
gem 'icalendar'
gem 'iso_country_codes'
gem 'jbuilder'
gem 'jquery-qtip2-wrapper-rails'
gem 'jquery-rails'
gem 'jquery-simplecolorpicker-rails'
gem 'jquery-turbolinks'
gem 'kt-paperclip'
gem 'linkeddata'
gem 'money-rails'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth_openid_connect'
gem 'pg'
gem 'private_address_check'
gem 'public_activity'
gem 'pundit'
gem 'rack-cors', require: 'rack/cors'
gem 'rails-i18n'
gem 'rails_admin'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redcarpet'
gem 'redis'
gem 'rest-client'
gem 'reverse_markdown'
gem 'rss'
gem 'sass-rails'
gem 'sassc-rails'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sentry-sidekiq'
gem 'sidekiq'
gem 'sidekiq-status'
gem 'simple_calendar', '~> 2.4'
gem 'simple_form'
gem 'simple_token_authentication'
gem 'sitemap-parser'
gem 'slim'
gem 'sunspot_rails', github: 'sunspot/sunspot', branch: 'master' # Contains Ruby 3 fixes that are not released
gem 'terser'
gem 'tess_rdf_extractors', git: 'https://github.com/ElixirTeSS/TeSS_RDF_Extractors', tag: '1.0.0'
gem 'turbolinks'
gem 'tzinfo'
gem 'tzinfo-data'
gem 'validate_url'
gem 'whenever'
gem 'will_paginate'

source 'https://rails-assets.org' do
  gem 'rails-assets-clipboard', '~> 1.5.12'
  gem 'rails-assets-devbridge-autocomplete', '~> 1.4.9'
  gem 'rails-assets-eonasdan-bootstrap-datetimepicker', '~> 4.17.42'
  gem 'rails-assets-markdown-it', '~> 7.0.1'
  gem 'rails-assets-moment', '~> 2.15.0'
  gem 'rails-assets-select2', '~> 4.0.8'
end

group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-lcov', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen'
  gem 'puma'
  gem 'web-console'
end

group :test do
  gem 'committee'
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'vcr'
  gem 'webmock'
end
