# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '8.1.2'

gem 'active_model_serializers' # Source of: ActiveSupport::Configurable is deprecated without replacement, and will be removed in Rails 8.2.
gem 'activerecord-session_store'
gem 'addressable'
gem 'ahoy_matey'
gem 'auto_strip_attributes'
gem 'bootsnap', require: false
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-sass'
gem 'bootstrap-tab-history-rails'
gem 'country_select'
gem 'devise'
gem 'devise_invitable'
gem 'eventbrite_sdk'
gem 'font-awesome-sass', '~> 4.7.0' # Prefer V4 icon styles
gem 'friendly_id'
gem 'geocoder'
gem 'gravtastic'
gem 'handlebars_assets'
gem 'httparty'
gem 'i18n_data'
gem 'icalendar'
gem 'iso_country_codes'
gem 'jbuilder'
gem 'jquery-qtip2-wrapper-rails'
gem 'jquery-rails'
gem 'jquery-simplecolorpicker-rails'
gem 'jquery-turbolinks'
gem 'kt-paperclip'
gem 'linkeddata'
gem 'maxmind-db'
gem 'money-rails'
gem 'oai'
gem 'omniauth_openid_connect'
gem 'omniauth-rails_csrf_protection'
gem 'pg'
gem 'private_address_check'
gem 'public_activity'
gem 'pundit'
gem 'rack-cors', require: 'rack/cors'
gem 'rails_admin'
gem 'rails-i18n'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'redcarpet'
gem 'redis'
gem 'rest-client'
gem 'reverse_markdown'
gem 'rss'
gem 'ruby-openai'
gem 'sassc-rails'
gem 'sass-rails'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sentry-sidekiq'
gem 'sidekiq'
gem 'sidekiq-status'
gem 'simple_calendar', '~> 2.4'
gem 'simple_form'
gem "simple_token_authentication", git: 'https://github.com/gonzalo-bulnes/simple_token_authentication.git', ref: 'f1cba4e' # Rails 8 support not yet released on Rubygems
gem 'sitemap_generator'
gem 'sitemap-parser'
gem 'slim'
gem 'sunspot_rails'
gem 'terser'
gem 'tess_rdf_extractors', git: 'https://github.com/ElixirTeSS/TeSS_RDF_Extractors', branch: 'master'
gem 'turbolinks'
gem 'tzinfo'
gem 'tzinfo-data'
gem 'validate_url'
gem 'whenever', require: false # Work around https://github.com/javan/whenever/issues/831
gem 'will_paginate'

group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-lcov', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen'
  gem 'puma'
  gem 'web-console'
end

group :test do
  gem 'committee'
  gem 'minitest'
  gem 'minitest-mock'
  gem 'minitest-reporters'
  gem 'rails-controller-testing'
  gem 'vcr'
  gem 'webmock'
end
