# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:  
    working_directory: '~/TeSS'
    docker: 
      - image: cimg/ruby:2.5.8-node
        environment: 
          PGHOST: localhost
          PGUSER: TeSS
          RAILS_ENV: test
      - image: postgres:12
        environment: 
          POSTGRES_USER: root 
          POSTGRES_DB: circle-test_test
          POSTGRES_PASSWORD: awesome-complex-password
    steps: 
      - checkout
      - run:
          name: install gems
          command: |
            pwd;
            gem install bundler -v '~> 2.2.27'
            bundle install;
            ruby --version;
            bundle --version;
            rails --version;
            rake --version;

      - run:
          name: install ImageMagick
          command: |
            sudo apt-get update && sudo apt-get install -y imagemagick
      - run:
          name: TeSS tests and coverage reporting
          command: |
            pwd;
            cp config/tess.example.yml config/tess.yml;
            cp config/secrets.circle.yml config/secrets.yml;
            cp config/ingestion.example.yml config/ingestion.yml;
            rake db:setup RAILS_ENV=test;
            rake test;
      - run:
          name: Submit Codacy report
          command: |
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov/TeSS.lcov;         
