
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "0 2 * * 1"  # at 2:00AM on Monday
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-pod
              image: postgres:14-alpine
              envFrom:
                - secretRef:
                    name: app-secrets-env
              env:
                - name: PGHOST
                  value: db-service
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets-env
                      key: DB_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets-env
                      key: DB_PASSWORD
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets-env
                      key: DB_NAME
              command: ["/bin/sh", "-c"]
              args:
                - |
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S) && \
                  mkdir -p /backups && \
                  pg_dump -Fc "$DB_NAME" > "/backups/${DB_NAME}_${TIMESTAMP}.dump"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
