# Complete config with all options enabled
default: &default
  base_url: http://localhost:3000
  contact_email: contact@example.com
  sender_email: no-reply@localhost
  twitter_handle: '@handle'
  solr_enabled: true
  solr_facets:
    events: [content_provider, keywords, event_types]
  announcement_message: Test 123
  prevent_robot_indexing: false
  require_cookie_consent: true
  blocked_domains:
    - !ruby/regexp '/bad-domain\.example/'
  i18n:
    available_locales:
      - en
    default_locale: en
    fallback_strategy: manual
  site:
    title: 'TeSS (Training eSupport System)'
    title_short: TeSS
    favicon: elixir/favicon.png
    logo: elixir/elixir-tess.svg
    logo_alt: 'Training eSupport System'
    logo_open_graph: ''
    logo_email: ''
    # Colours of the SVG icons used throughout TeSS, requires `rake assets:precompile` if changed
    icon_primary_color: '#047EAA' # Blue by default
    icon_secondary_color: '#F47D21' # Orange by default
    repository: 'https://github.com/ElixirTeSS/TeSS'
    supported_by: 'elixir_supported_by'
    widget_example:
    home_page: # Configuration for the sections displayed on the front page
      catalogue_blocks: true
      provider_carousel: true
      # A list of content provider IDs to show in the front page carousel. Leave blank to show latest 5 (that have avatars set)
      featured_providers: [1]
      faq: [who, how, why, embed, subscribe] # Questions/answers in config/en.yml: home > faq. Use empty array to hide section
      promo_blocks: false
    # The order in which the tabs appear (if feature enabled)
    tab_order: ['about', 'events', 'materials', 'elearning_materials', 'workflows', 'collections', 'trainers', 'content_providers', 'nodes']
    # The tabs that should be collapsed under the "Directory" tab. Can be left blank to hide it.
    directory_tabs: ['trainers', 'content_providers', 'nodes']
    n_provider_ids: 5
  mailer:
    delivery_method: sendmail
    location: /usr/sbin/sendmail
    arguments: '-i -t'
  gmaps:
    center:
      latitude: 53.4674583
      longitude: -2.233948899999973
    zoom:
      latitude: 3
      longitude: 13
  header_notice: # HTML to display above the header
  feature:
    elearning_materials: false
    events: true
    invitation: false
    materials: true
    nodes: false
    collections: true
    content_providers: true
    subscription: true
    registration: true
    trainers: false
    workflows: true
    sources: false
    user_source_creation: true
    edit_suggestions: false
    geocoding: false
    # Possible features to disable:
    #  biotools, topics, operations, sponsors, fairshare, county, ardc_fields_of_research,
    #  other_types, subsets, syllabus, approved_editors address_finder
    disabled: ['ardc_fields_of_research', 'other_types', 'subsets', 'syllabus', 'approved_editors']
    materials_disabled: [status]
  restrict_content_provider_selection: false
  user_ingestion_methods: ['bioschemas']
  placeholder:
    collection: 'placeholder-collection.svg'
    content_provider: 'placeholder-organization.svg'
    person: 'placeholder-person.svg'
  dictionaries:
    cost_basis: 'cost_basis.yml'
    difficulty: 'difficulty.yml'
    eligibility: 'eligibility.yml'
    event_types: 'event_types.yml'
    licences: 'licences.yml'
    material_status: 'material_status.yml'
    material_type: 'material_type.yml'
    target_audience: 'target_audience.yml'
    trainer_experience: 'trainer_experience.yml'
    online_keywords: 'online_keywords.yml'
  funders:
    - url: https://www.oscars-project.eu/projects/mtess-x-scaling-training-portal-federation-ris-through-multi-tenanting-and-exchange
      logo: elixir/oscars-logo.svg
    - url: https://biofair.uk/
      logo: elixir/biofair-logo.png
    - url: https://elixir.ut.ee/
      logo: nodes/logos_svg/EE.svg
    - url: http://elixir-uk.org/
      logo: nodes/logos_svg/GB.svg
    - url: http://www.bbsrc.ac.uk/research/grants/grants/AwardDetails.aspx?FundingReference=BB/L005050/1
      logo: elixir/bbsrc-logo.svg
    - url: http://www.manchester.ac.uk/
      logo: elixir/uom-logo.svg
    - url: http://www.oerc.ox.ac.uk/
      logo: elixir/oerc-logo.svg

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
