<%
  db_secrets = YAML.load(File.read(Rails.root.join('config', 'secrets.yml')), aliases: true).dig(Rails.env, 'database')
%>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { db_secrets[:host] } %>
  port: <%= ENV.fetch("DB_PORT") { db_secrets[:port] } %>
  database: <%= ENV.fetch("DB_NAME") { db_secrets[:name] } %>
  username: <%= ENV.fetch("DB_USER") { db_secrets[:username] } %>
  password: <%= ENV.fetch("DB_PASSWORD") { db_secrets[:password] } %>

<% if Rails.env.development? %>
development:
  <<: *default
<% end %>

<% if Rails.env.test? %>
test:
  <<: *default
<% end %>

<% if Rails.env.production? %>
production:
  <<: *default
<% end %>
