name: Docker tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup
        run: | 
          cp env.sample .env
          cp config/tess.example.yml config/tess.yml
          cp config/secrets.example.yml config/secrets.yml
      - name: Build
        run: docker compose build test
      - name: Test
        run: docker compose run test
